import type { Metadata } from 'next'
import Navbar from '../../ui/navbar/Navbar'
import Sidebar from '../../ui/sidebar/Sidebar';
import { CartProvider } from '../../context/cartContext';
import { ProductProvider } from '../../context/productContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <CartProvider>
        <ProductProvider>
          <Navbar/>
          <div style={{display: 'flex', flexDirection: 'row'}}>
            <Sidebar/>
            {children}
          </div>
        </ProductProvider>
      </CartProvider>
      
    </div>
  )
}