import Navbar from '@/ui/navbar/Navbar'
import type { Metadata } from 'next'
import Sidebar from '../../ui/sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Navbar/>
      <div style={{display: 'flex', flexDirection: 'row'}}>
        <Sidebar/>
        {children}
      </div>
      
    </div>
  )
}