import Navbar from '@/ui/navbar/Navbar'
import type { Metadata } from 'next'
import Sidebar from '../../ui/sidebar/Sidebar';
import { CartProvider } from '@/context/cartContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <CartProvider>
        <Navbar/>
        <div style={{display: 'flex', flexDirection: 'row'}}>
          <Sidebar/>
          {children}
        </div>
      </CartProvider>
      
    </div>
  )
}