import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/context/cartContext'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ProductProvider } from '@/context/productContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = { 
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider
        loginUrl='/home'
      >
        <body className={inter.className}>
          {/* <ProductProvider> */}
            {/* <CartProvider> */}
              {children}  
            {/* </CartProvider> */}
          {/* </ProductProvider> */}
        </body>
      </UserProvider>
    </html>
  )
}
