// Generated by https://quicktype.io

export interface PurchaseResponse {
  status: boolean;
  data:   Purchase[];
}

export interface Purchase {
  _id:         string;
  products:    Product[];
  transaction: string;
  isApproved:  boolean;
  userId:      string;
  total:       number;
  status:      boolean;
  __v:         number;
}

export interface Product {
  description: string;
  price:       number;
  name:        string;
  image:       string;
  _id:         string;
  quantity:    string;
}
