export interface UserCreateInput {
  name: string;
  lastname: string;
  email: string;
  role: string;
  identification: string | any;
  status: boolean;
}

// Generated by https://quicktype.io

export interface UserCreateResponse {
  status:  boolean;
  message: string;
  data:    User;
}

export interface User {
  name:           string;
  lastname:       string;
  email:          string;
  role:           string;
  identification: string;
  status:         boolean;
  _id:            string;
  __v:            number;
}
